layout_spectrum: 0.6795046
typography_spectrum: 0.9485149
color:
  saturation: 0.5670314
  lightness: 0.3927205
  brandStrength: 0.9533949
  rhythmicContrast: 0.8099614
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: SimpleDesign
