name: SimpleDesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04869
title: Simple Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12171b'
    - '#ebece7'
    - '#403835'
    - '#6b5a52'
    - '#94867d'
  brandStrength: 0.5
  lightness: 0.3927205
  saturation: 0.5670314
  rhythmicContrast: 0.8099614
purpose: []
